### ISSUE TITLE
490版本微调报错

### ISSUE THREAD

**Issue by jyC23333** [THUDM/CogVLM#102]
8*V100

不清楚V100是否支持微调？
```bash
bash scripts/finetune_490_lora.sh
```


```
NCCL_DEBUG=info NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=2 LOCAL_WORLD_SIZE=8 SAT_HOME=~/.sat_models deepspeed --master_port 16666 --hostfile hostfile finetune_demo.py --experiment-name finetune-cogvlm-base-490 --model-parallel-size 
1 --mode finetune --train-iters 800 --resume-dataloader --from_pretrained cogvlm-base-490 --max_length 1288 --lora_rank 10 --use_lora --local_tokenizer lmsys/vicuna-7b-v1.5 --version base --train-data ./archive_split/train --vali
d-data ./archive_split/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --vit_checkpoint_activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eva
l-batch-size 1 --split 1. --deepspeed_config scripts/test_config_bf16_490.json --skip-init --seed 2023                                                                                                                               
[2023-11-16 18:03:38,192] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)                                                                                                              
[2023-11-16 18:04:11,186] [WARNING] [runner.py:203:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.                                                                                    
[2023-11-16 18:04:11,186] [INFO] [runner.py:570:main] cmd = /data/Anaconda/anaconda3/envs/CogVLM/bin/python3.8 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN119 --master_addr=127.0.
0.1 --master_port=16666 --enable_each_rank_log=None finetune_demo.py --experiment-name finetune-cogvlm-base-490 --model-parallel-size 1 --mode finetune --train-iters 800 --resume-dataloader --from_pretrained cogvlm-base-490 --max
_length 1288 --lora_rank 10 --use_lora --local_tokenizer lmsys/vicuna-7b-v1.5 --version base --train-data ./archive_split/train --valid-data ./archive_split/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --
checkpoint-activations --vit_checkpoint_activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config scripts/test_config_bf16_490.json --skip-init --se
ed 2023                                                                                                                                                                                                                              
[2023-11-16 18:04:16,112] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)                                                                                                              
[2023-11-16 18:04:20,248] [INFO] [launch.py:138:main] 0 NCCL_IB_DISABLE=0                                                                                                                                                            
[2023-11-16 18:04:20,248] [INFO] [launch.py:138:main] 0 NCCL_DEBUG=info                                                                                                                                                              
[2023-11-16 18:04:20,248] [INFO] [launch.py:138:main] 0 NCCL_NET_GDR_LEVEL=2                                                                                                                                                         
[2023-11-16 18:04:20,248] [INFO] [launch.py:138:main] 0 BRAIN_NCCL_IB_TC=106                                                                                                                                                         
[2023-11-16 18:04:20,248] [INFO] [launch.py:138:main] 0 BRAIN_NCCL_IB_GID_INDEX=3                                                                                                                                                    
[2023-11-16 18:04:20,249] [INFO] [launch.py:138:main] 0 BRAIN_NCCL_IB_HCA=mlx5_51
[2023-11-16 18:04:20,249] [INFO] [launch.py:138:main] 0 BRAIN_NCCL_SOCKET_IFNAME=eth0
[2023-11-16 18:04:20,249] [INFO] [launch.py:138:main] 0 BRAIN_NCCL_IB_DISABLE=0
[2023-11-16 18:04:20,249] [INFO] [launch.py:138:main] 0 BRAIN_NCCL_IB_CUDA_SUPPORT=1
[2023-11-16 18:04:20,249] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]}
[2023-11-16 18:04:20,249] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=8, node_rank=0
[2023-11-16 18:04:20,249] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]})
[2023-11-16 18:04:20,249] [INFO] [launch.py:163:main] dist_world_size=8
[2023-11-16 18:04:20,249] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
[2023-11-16 18:04:24,364] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-16 18:04:24,505] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-16 18:04:24,521] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-16 18:04:24,591] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-16 18:04:24,711] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-16 18:04:24,747] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-16 18:04:24,817] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-16 18:04:24,836] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-16 18:04:43,170] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-11-16 18:04:43,170] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-11-16 18:04:43,170] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-11-16 18:04:43,171] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-11-16 18:04:43,171] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-11-16 18:04:43,171] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-11-16 18:04:43,171] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-11-16 18:04:43,172] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-11-16 18:04:47,551] [INFO] using world size: 8 and model-parallel size: 1 
[2023-11-16 18:04:47,551] [INFO] > padded vocab (size: 100) with 28 dummy tokens (new size: 128)
[2023-11-16 18:04:47,552] [INFO] Will override arguments with manually specified deepspeed_config!
[2023-11-16 18:04:48,815] [INFO] [RANK 0] > initializing model parallel with size 1
[2023-11-16 18:04:48,913] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-16 18:04:48,913] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-16 18:04:48,913] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-16 18:04:48,914] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-16 18:04:48,914] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-16 18:04:48,917] [INFO] [checkpointing.py:1032:_configure_using_config_file] {'partition_activations': False, 'contiguous_memory_optimization': False, 'cpu_checkpointing': False, 'number_checkpoints': None, 'synchronize_checkpoint_boundary': False, 'profile': False}
[2023-11-16 18:04:48,917] [INFO] [checkpointing.py:227:model_parallel_cuda_manual_seed] > initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 4741 and data parallel seed: 2023
[2023-11-16 18:04:48,922] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-16 18:04:48,922] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-16 18:04:48,923] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-16 18:04:48,947] [INFO] [RANK 0] building FineTuneTrainCogVLMModel model ...
[2023-11-16 18:05:05,116] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 17639685376
[2023-11-16 18:05:26,454] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 890
[2023-11-16 18:05:28,156] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 891
[2023-11-16 18:05:29,202] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 892
[2023-11-16 18:05:29,860] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 893
[2023-11-16 18:05:30,437] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 894
[2023-11-16 18:05:31,096] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 895
[2023-11-16 18:05:31,098] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 896
[2023-11-16 18:05:31,100] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 897
[2023-11-16 18:05:31,100] [ERROR] [launch.py:321:sigkill_handler] ['/data/Anaconda/anaconda3/envs/CogVLM/bin/python3.8', '-u', 'finetune_demo.py', '--local_rank=7', '--experiment-name', 'finetune-cogvlm-base-490', '--model-parallel-size', '1', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', 'cogvlm-base-490', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', 'lmsys/vicuna-7b-v1.5', '--version', 'base', '--train-data', './archive_split/train', '--valid-data', './archive_split/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'scripts/test_config_bf16_490.json', '--skip-init', '--seed', '2023'] exits with return code = -9
```

**Comment by 1049451037** [comment]
可以通过修改MP_SIZE节省显存：

https://github.com/THUDM/CogVLM/blob/3c254565408e180207de8a0b69f20473ecd5c157/scripts/finetune_490_lora.sh#L6

**Comment by jyC23333** [comment]
![image](https://github.com/THUDM/CogVLM/assets/110331827/02a13f5b-036b-43c1-8132-8e357b07f4a1)
@1049451037 这应该是最小了吧？8*V100大概256GB，是因为显存不太够吗？

**Comment by 1049451037** [comment]
MP_SIZE是模型并行数，并行数越大占用显存越小。

32G显然不够，模型的checkpoint文件就34G了。一张卡根本装不下模型，只能用并行。

**Comment by jyC23333** [comment]
@1049451037 
![image](https://github.com/THUDM/CogVLM/assets/110331827/63fa7e3b-2f90-4568-8bb2-3d26d82a5a80)
这个配置还是报上面的错

另外，一块A100可以正常训起来

**Comment by 1049451037** [comment]
那可能问题不在于显存不够，而是内存不够，多插几个内存条吧。

**Comment by jyC23333** [comment]
@1049451037 还有个问题想请教下：
执行完这一步后
![image](https://github.com/THUDM/CogVLM/assets/110331827/6521208e-42eb-46d2-993f-f70de56a3bf4)
这三个文件是什么关系？加起来有200多个G
![image](https://github.com/THUDM/CogVLM/assets/110331827/7631961d-6632-4c72-a0ba-3f41944a2b8f)
如果我想用合并完的模型进行本地的inference，要怎么操作？

**Comment by 1049451037** [comment]
finetune目录是微调过程中保存的中间检查点，每隔一定的step就会保存一次，所以比较大。merged_lora是把lora整合会模型里，merged_model是把模型并行合并为1个完整的模型（如果你没有使用模型并行可以不管）。merged操作是为了让模型对齐原始的CogVLM格式，从而可以用cli_demo.py加载。

**Comment by jyC23333** [comment]
@1049451037  明白了，感谢！

**Comment by jyC23333** [comment]
@1049451037 另外，关于迁移至下游任务上还有几点疑问想交流下：
1. 之前在LLM上训练时，感觉通过lora的方式不太容易让模型学会新的知识，而是更容易去学说话风格或者学会新的prompt模板，那在VLM上lora训练会怎样影响模型？
2. 我需要准备的数据量一般在什么量级时，能尝试训练lora？
3. repo里没有找到进行全量微调的教程，当前的代码支持全量微调吗？

**Comment by 1049451037** [comment]
关于具体训练只能自己尝试，我也不太清楚。

全量微调可以自行配置可训练参数：

https://github.com/THUDM/CogVLM/blob/3c254565408e180207de8a0b69f20473ecd5c157/finetune_demo.py#L13-L36
