### ISSUE TITLE
merge_model遇到瓶颈

### ISSUE THREAD

**Issue by banzhuan37** [THUDM/CogVLM#303]
### System Info / 系統信息

ubuntu

### Who can help? / 谁可以帮助到您？

你好：

现在我在本地finetune了cogvlm-chat-v1.1，遇到了如下两个问题想咨询。
1. 我们想让模型能识别unseen的物体并产生描述，数据量大约在2000张图片，请问默认的训练策略上有哪些建议调整的参数。
2. 我们finetune后的checkpoints生成了rank00到rank03，各17G的文件，运行merge_model.py的时候报cuda out of memory，我们的调试设备是六卡24g的4090，请问merge model需要多大的显存或者有没有降低显存需求的方案。

非常感谢帮助。

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行merge_model.py报错，cuda out of memory

### Expected behavior / 期待表现

希望能提供相关指导意见

**Comment by 1049451037** [comment]
merge_model需要用torchrun多卡启动，卡的数量等于你运行的MP_SIZE。

```
torchrun --standalone --nnodes=1 --nproc-per-node=4 merge_model.py --from_pretrained xxx --bf16
```

**Comment by banzhuan37** [comment]
torchrun --standalone --nnodes=1 --nproc-per-node=6 merge_model.py --from_pretrained xxx --bf16 --version chat_old 
我用的就是这行命令，
![捕获](https://github.com/THUDM/CogVLM/assets/65010776/c02057ba-d2dc-46bd-8351-a33c237ae65c)

**Comment by banzhuan37** [comment]
> merge_model需要用torchrun多卡启动，卡的数量等于你运行的MP_SIZE。
> 
> ```
> torchrun --standalone --nnodes=1 --nproc-per-node=4 merge_model.py --from_pretrained xxx --bf16
> ```

六张卡先是每张占用10G显存，然后提示loading model 然后就开始cuda memory报错，报错的时候每张卡都接近24G的显存

**Comment by 1049451037** [comment]
试一下安装新版的sat：

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install . --no-deps
```

**Comment by banzhuan37** [comment]
SAT已经是0.4.9版本。请问一下正常merge model需要多少显存

**Comment by 1049451037** [comment]
你不是说“我们finetune后的checkpoints生成了rank00到rank03”吗？为什么要用6。应该用4。

**Comment by 1049451037** [comment]
至于显存，能正常训练就能正常merge。

**Comment by 1049451037** [comment]
> 试一下安装新版的sat：
> 
> ```
> git clone https://github.com/THUDM/SwissArmyTransformer
> cd SwissArmyTransformer
> pip install . --no-deps
> ```

请安装github最新版。

**Comment by banzhuan37** [comment]
你好，谢谢你的意见，更新了最新的SAT还是报显存溢出错误。我看SAT最新版，2天前提交的operation文件的修改也没解决这个问题。我是四卡训，四卡merge。这个问题和apex那个库的安装有关系吗

**Comment by 1049451037** [comment]
和apex没有关系，可能merge操作确实会占用多一点显存，单卡显存至少需要

【模型大小】/ 4 + 【模型里最大的一个Tensor】* 4

这么大的显存

**Comment by 1049451037** [comment]
您是否有足够的cpu内存？如果cpu内存够大的话我可以改一下在cpu上merge

**Comment by banzhuan37** [comment]
万分感谢 我们有258G的内存

**Comment by banzhuan37** [comment]
显存溢出的问题解决了，原因是我们指定了中间的finetune结果，漏掉了latest链接。默认用最后一次finetune的结果可以成功merge。但是在最后一部会报错：The size of  tensor a (1792) must match the size of tensor b (448) at non-singleton dimension 0. 请问这个如何解决。
谢谢你们提供的帮助

**Comment by 1049451037** [comment]
中间finetune的结果需要先把lora给merge了，才能继续merge_model。参考这个：https://github.com/THUDM/CogVLM/issues/142

在cpu上merge可以pull一下最新的sat，然后使用下面这一版merge_model代码：

```python
# -*- encoding: utf-8 -*-
import os, sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import torch
torch.cuda.is_available = lambda : False

import argparse
from models.cogvlm_model import FineTuneTestCogVLMModel
from sat.training.model_io import save_checkpoint

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", type=str, default="base", help='version to interact with')
    parser.add_argument("--from_pretrained", type=str, default="checkpoints/merged_lora", help='pretrained ckpt')
    parser.add_argument("--fp16", action="store_true")
    parser.add_argument("--bf16", action="store_true")
    args = parser.parse_args()
    rank = int(os.environ.get('RANK', 0))
    world_size = int(os.environ.get('WORLD_SIZE', 1))
    parser = FineTuneTestCogVLMModel.add_model_specific_args(parser)
    args = parser.parse_args()

    # load model
    model, model_args = FineTuneTestCogVLMModel.from_pretrained(
        args.from_pretrained,
        args=argparse.Namespace(
        deepspeed=None,
        local_rank=rank,
        rank=rank,
        world_size=world_size,
        model_parallel_size=world_size,
        mode='inference',
        skip_init=True,
        use_gpu_initialization=True if torch.cuda.is_available() else False,
        device='cpu',
        **vars(args)
    ), url='local', overwrite_args={'model_parallel_size': 1})
    model = model.eval()
    model_args.save = './checkpoints/merged_model_{}'.format(model_args.eva_args["image_size"][0])
    save_checkpoint(1, model, None, None, model_args)

if __name__ == "__main__":
    main()
```

**Comment by 1049451037** [comment]
不过我没太听懂的是到底成功merge了……还是报错了……为什么说“可以成功merge”，但是“报错”……

**Comment by banzhuan37** [comment]
![13](https://github.com/THUDM/CogVLM/assets/65010776/2cf7aa4b-debf-4fca-b9b1-1866e2ccd3bd)
![12](https://github.com/THUDM/CogVLM/assets/65010776/62fe0964-9a3e-4137-8b55-497a619a3c76)
没有成功merge，只是显存溢出的问题解决了。现在出现的新问题是在initializing model parallel with size 4 时报错。提示两个tensor无法对齐

**Comment by 1049451037** [comment]
这个问题是你需要先merge lora，上面已经说过了。

> 中间finetune的结果需要先把lora给merge了，才能继续merge_model。参考这个：#142
> 
> 在cpu上merge可以pull一下最新的sat，然后使用下面这一版merge_model代码：
> 
> ```python
> # -*- encoding: utf-8 -*-
> import os, sys
> sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
> 
> import torch
> torch.cuda.is_available = lambda : False
> 
> import argparse
> from models.cogvlm_model import FineTuneTestCogVLMModel
> from sat.training.model_io import save_checkpoint
> 
> def main():
>     parser = argparse.ArgumentParser()
>     parser.add_argument("--version", type=str, default="base", help='version to interact with')
>     parser.add_argument("--from_pretrained", type=str, default="checkpoints/merged_lora", help='pretrained ckpt')
>     parser.add_argument("--fp16", action="store_true")
>     parser.add_argument("--bf16", action="store_true")
>     args = parser.parse_args()
>     rank = int(os.environ.get('RANK', 0))
>     world_size = int(os.environ.get('WORLD_SIZE', 1))
>     parser = FineTuneTestCogVLMModel.add_model_specific_args(parser)
>     args = parser.parse_args()
> 
>     # load model
>     model, model_args = FineTuneTestCogVLMModel.from_pretrained(
>         args.from_pretrained,
>         args=argparse.Namespace(
>         deepspeed=None,
>         local_rank=rank,
>         rank=rank,
>         world_size=world_size,
>         model_parallel_size=world_size,
>         mode='inference',
>         skip_init=True,
>         use_gpu_initialization=True if torch.cuda.is_available() else False,
>         device='cpu',
>         **vars(args)
>     ), url='local', overwrite_args={'model_parallel_size': 1})
>     model = model.eval()
>     model_args.save = './checkpoints/merged_model_{}'.format(model_args.eva_args["image_size"][0])
>     save_checkpoint(1, model, None, None, model_args)
> 
> if __name__ == "__main__":
>     main()
> ```

**Comment by banzhuan37** [comment]
非常感谢帮助，已经成功运行了
