### ISSUE TITLE
Colab basic_demo fails - Model: libcuda.so cannot found! 

### ISSUE THREAD

**Issue by wenshutang** [THUDM/CogVLM#324]
### System Info / 系統信息

I am running this on a A100 GPU colab instance

```
nvidia-smi

Wed Jan 17 03:32:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P0              44W / 400W |      2MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

```
!ldconfig -p | grep libcuda
libcudart.so.12 (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12
libcudart.so (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so
```

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```
python cli_demo_sat.py --from_pretrained cogagent-chat --version chat --fp16 --stream_chat

[2024-01-17 03:44:24,191] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2024-01-17 03:44:31.566110: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-17 03:44:31.566157: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-17 03:44:31.567922: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-17 03:44:33.057938: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Please build and install Nvidia apex package with option '--cuda_ext' according to https://github.com/NVIDIA/apex#from-source .
[2024-01-17 03:44:35,840] [INFO] building CogAgentModel model ...
[2024-01-17 03:44:35,841] [INFO] [RANK 0] > initializing model parallel with size 1
[2024-01-17 03:44:35,842] [INFO] [RANK 0] You didn't pass in LOCAL_WORLD_SIZE environment variable. We use the guessed LOCAL_WORLD_SIZE=1. If this is wrong, please pass the LOCAL_WORLD_SIZE manually.
[2024-01-17 03:44:35,842] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
[2024-01-17 03:45:34,261] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 18291033280
INFO:sat:[RANK 0]  > number of parameters on model parallel rank 0: 18291033280
[2024-01-17 03:45:43,411] [INFO] [RANK 0] global rank 0 is loading checkpoint /root/.sat_models/cogagent-chat/1/mp_rank_00_model_states.pt
INFO:sat:[RANK 0] global rank 0 is loading checkpoint /root/.sat_models/cogagent-chat/1/mp_rank_00_model_states.pt
[2024-01-17 03:48:12,173] [INFO] [RANK 0] > successfully loaded /root/.sat_models/cogagent-chat/1/mp_rank_00_model_states.pt
INFO:sat:[RANK 0] > successfully loaded /root/.sat_models/cogagent-chat/1/mp_rank_00_model_states.pt
[Language processor version]: chat
Welcome to CogAgent-CLI. Enter an image URL or local file path to load an image. Continue inputting text to engage in a conversation. Type "clear" to start over, or "stop" to end the program.
Please enter the image path or URL: /content/images/kamara-loan.png
User: what's the title of the article
Model: libcuda.so cannot found!
```

### Expected behavior / 期待表现

I am not able to get inference results due to the 
```
Model: libcuda.so cannot found!
```
Running this on fp16

**Comment by zRzRzRzRzRzRzR** [comment]
This problem is not a problem with the model, but a problem with the CUDA installation process. It is recommended to check the environment configuration.

**Comment by wenshutang** [comment]
Thank you for the response. Turns out I needed to install Cuda in addition to the cudart libs on colab.

```
apt-get update
apt-get install cuda
```
```
ldconfig -p | grep libcuda
	libcudart.so.12 (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12
	libcudart.so.12 (libc6,x86-64) => /usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudart.so.12
	libcudart.so (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so
	libcudart.so (libc6,x86-64) => /usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudart.so
	libcudadebugger.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcudadebugger.so.1
	libcuda.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcuda.so.1
	libcuda.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcuda.so
```

You may mark this resolved.
