### ISSUE TITLE
Unrecognized arguments during fine-tuning

### ISSUE THREAD

**Issue by Baggiorobertozoba** [THUDM/CogVLM#380]
NCCL_DEBUG=info NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=2 LOCAL_WORLD_SIZE=8 SAT_HOME=~/.sat_models deepspeed --master_port 16666 --hostfile hostfile /CogVLM/finetune_demo/finetune_cogvlm_demo.py --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --model-parallel-size 8 --mode finetune --train-iters 800 --resume-dataloader --from_pretrained /workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --max_length 1288 --lora_rank 10 --use_lora --local_tokenizer /workspace/models--lmsys--vicuna-7b-v1.5 --version chat_old --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --vit_checkpoint_activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
[2024-02-14 00:09:06,409] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 00:09:07,460] [WARNING] [runner.py:202:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-02-14 00:09:07,460] [INFO] [runner.py:568:main] cmd = /opt/conda/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN119 --master_addr=127.0.0.1 --master_port=16666 --enable_each_rank_log=None /CogVLM/finetune_demo/finetune_cogvlm_demo.py --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --model-parallel-size 8 --mode finetune --train-iters 800 --resume-dataloader --from_pretrained /workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --max_length 1288 --lora_rank 10 --use_lora --local_tokenizer /workspace/models--lmsys--vicuna-7b-v1.5 --version chat_old --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --vit_checkpoint_activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
[2024-02-14 00:09:10,328] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 00:09:11,382] [INFO] [launch.py:138:main] 0 NCCL_IB_DISABLE=0
[2024-02-14 00:09:11,382] [INFO] [launch.py:138:main] 0 NCCL_DEBUG=info
[2024-02-14 00:09:11,382] [INFO] [launch.py:138:main] 0 NCCL_NET_GDR_LEVEL=2
[2024-02-14 00:09:11,382] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.17.1-1+cuda12.1
[2024-02-14 00:09:11,382] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.17.1-1
[2024-02-14 00:09:11,382] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.17.1-1
[2024-02-14 00:09:11,382] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2024-02-14 00:09:11,382] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.17.1-1+cuda12.1
[2024-02-14 00:09:11,382] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2024-02-14 00:09:11,382] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.17.1-1
[2024-02-14 00:09:11,382] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]}
[2024-02-14 00:09:11,382] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=8, node_rank=0
[2024-02-14 00:09:11,382] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]})
[2024-02-14 00:09:11,382] [INFO] [launch.py:163:main] dist_world_size=8
[2024-02-14 00:09:11,382] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
[2024-02-14 00:09:11,384] [INFO] [launch.py:253:main] process 8660 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=0', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 00:09:11,385] [INFO] [launch.py:253:main] process 8661 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=1', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 00:09:11,386] [INFO] [launch.py:253:main] process 8662 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=2', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 00:09:11,387] [INFO] [launch.py:253:main] process 8663 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=3', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 00:09:11,388] [INFO] [launch.py:253:main] process 8664 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=4', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 00:09:11,389] [INFO] [launch.py:253:main] process 8665 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=5', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 00:09:11,390] [INFO] [launch.py:253:main] process 8666 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=6', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 00:09:11,391] [INFO] [launch.py:253:main] process 8667 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=7', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 00:09:14,547] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 00:09:14,569] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 00:09:14,569] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 00:09:14,580] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 00:09:14,615] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 00:09:14,615] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 00:09:14,634] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 00:09:14,644] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: unrecognized arguments: --local_rank=5 --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --model-parallel-size 8 --mode finetune --train-iters 800 --resume-dataloader --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: unrecognized arguments: --local_rank=7 --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --model-parallel-size 8 --mode finetune --train-iters 800 --resume-dataloader --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: unrecognized arguments: --local_rank=4 --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --model-parallel-size 8 --mode finetune --train-iters 800 --resume-dataloader --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: unrecognized arguments: --local_rank=1 --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --model-parallel-size 8 --mode finetune --train-iters 800 --resume-dataloader --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: unrecognized arguments: --local_rank=0 --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --model-parallel-size 8 --mode finetune --train-iters 800 --resume-dataloader --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: unrecognized arguments: --local_rank=3 --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --model-parallel-size 8 --mode finetune --train-iters 800 --resume-dataloader --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: unrecognized arguments: --local_rank=6 --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --model-parallel-size 8 --mode finetune --train-iters 800 --resume-dataloader --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: unrecognized arguments: --local_rank=2 --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt --model-parallel-size 8 --mode finetune --train-iters 800 --resume-dataloader --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
[2024-02-14 00:09:22,404] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 8660
[2024-02-14 00:09:22,434] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 8661
[2024-02-14 00:09:22,436] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 8662
[2024-02-14 00:09:22,438] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 8663
[2024-02-14 00:09:22,439] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 8664
[2024-02-14 00:09:22,439] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 8665
[2024-02-14 00:09:22,441] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 8666
[2024-02-14 00:09:22,442] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 8667
[2024-02-14 00:09:22,443] [ERROR] [launch.py:322:sigkill_handler] ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=7', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023'] exits with return code = 2

**Comment by Baggiorobertozoba** [comment]
**I have 8 GPU's. And now I'm receiving this error:**

NCCL_DEBUG=info NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=2 LOCAL_WORLD_SIZE=8 SAT_HOME=~/.sat_models deepspeed --master_port 16666 --hostfile hostfile /CogVLM/finetune_demo/finetune_cogvlm_demo.py --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1 --model-parallel-size 8 --mode finetune --train-iters 2000 --resume-dataloader --from_pretrained /workspace/cogvlm-chat-v1.1/1 --max_length 1288 --lora_rank 10 --use_lora --local_tokenizer /workspace/models--lmsys--vicuna-7b-v1.5 --version chat_old --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --vit_checkpoint_activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
[2024-02-14 17:34:47,770] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 17:34:48,610] [WARNING] [runner.py:202:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-02-14 17:34:48,610] [INFO] [runner.py:568:main] cmd = /opt/conda/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN119 --master_addr=127.0.0.1 --master_port=16666 --enable_each_rank_log=None /CogVLM/finetune_demo/finetune_cogvlm_demo.py --experiment-name finetune-/workspace/cogvlm-chat-v1.1/1 --model-parallel-size 8 --mode finetune --train-iters 2000 --resume-dataloader --from_pretrained /workspace/cogvlm-chat-v1.1/1 --max_length 1288 --lora_rank 10 --use_lora --local_tokenizer /workspace/models--lmsys--vicuna-7b-v1.5 --version chat_old --train-data /Dataset/train --valid-data /Dataset/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --vit_checkpoint_activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config test_config_bf16.json --skip-init --seed 2023
[2024-02-14 17:34:50,582] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 17:34:51,327] [INFO] [launch.py:138:main] 0 NCCL_IB_DISABLE=0
[2024-02-14 17:34:51,327] [INFO] [launch.py:138:main] 0 NCCL_DEBUG=info
[2024-02-14 17:34:51,327] [INFO] [launch.py:138:main] 0 NCCL_NET_GDR_LEVEL=2
[2024-02-14 17:34:51,327] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.17.1-1+cuda12.1
[2024-02-14 17:34:51,327] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.17.1-1
[2024-02-14 17:34:51,327] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.17.1-1
[2024-02-14 17:34:51,327] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2024-02-14 17:34:51,327] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.17.1-1+cuda12.1
[2024-02-14 17:34:51,327] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2024-02-14 17:34:51,327] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.17.1-1
[2024-02-14 17:34:51,327] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]}
[2024-02-14 17:34:51,327] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=8, node_rank=0
[2024-02-14 17:34:51,327] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]})
[2024-02-14 17:34:51,327] [INFO] [launch.py:163:main] dist_world_size=8
[2024-02-14 17:34:51,327] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
[2024-02-14 17:34:51,328] [INFO] [launch.py:253:main] process 13632 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=0', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '2000', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 17:34:51,329] [INFO] [launch.py:253:main] process 13633 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=1', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '2000', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 17:34:51,330] [INFO] [launch.py:253:main] process 13634 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=2', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '2000', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 17:34:51,331] [INFO] [launch.py:253:main] process 13635 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=3', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '2000', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 17:34:51,332] [INFO] [launch.py:253:main] process 13636 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=4', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '2000', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 17:34:51,333] [INFO] [launch.py:253:main] process 13637 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=5', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '2000', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 17:34:51,334] [INFO] [launch.py:253:main] process 13638 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=6', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '2000', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 17:34:51,335] [INFO] [launch.py:253:main] process 13639 spawned with command: ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=7', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '2000', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023']
[2024-02-14 17:34:53,656] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 17:34:53,656] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 17:34:53,656] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 17:34:53,671] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 17:34:53,696] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 17:34:53,702] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 17:34:53,711] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-02-14 17:34:53,716] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--local_rank LOCAL_RANK]
                               [--experiment-name finetune- EXPERIMENT_NAME FINETUNE_]
                               [--model-parallel-size MODEL_PARALLEL_SIZE]
                               [--train-iters TRAIN_ITERS]
                               [--resume-dataloader] [--train-data TRAIN_DATA]
                               [--valid-data VALID_DATA]
                               [--distributed-backend DISTRIBUTED_BACKEND]
                               [--lr-decay-style LR_DECAY_STYLE]
                               [--warmup WARMUP] [--checkpoint-activations]
                               [--save-interval SAVE_INTERVAL]
                               [--eval-interval EVAL_INTERVAL] [--save SAVE]
                               [--eval-iters EVAL_ITERS]
                               [--eval-batch-size EVAL_BATCH_SIZE]
                               [--split SPLIT]
                               [--deepspeed_config DEEPSPEED_CONFIG]
                               [--skip-init] [--seed SEED]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: argument --model-parallel-size: invalid int value: 'finetune'
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--local_rank LOCAL_RANK]
                               [--experiment-name finetune- EXPERIMENT_NAME FINETUNE_]
                               [--model-parallel-size MODEL_PARALLEL_SIZE]
                               [--train-iters TRAIN_ITERS]
                               [--resume-dataloader] [--train-data TRAIN_DATA]
                               [--valid-data VALID_DATA]
                               [--distributed-backend DISTRIBUTED_BACKEND]
                               [--lr-decay-style LR_DECAY_STYLE]
                               [--warmup WARMUP] [--checkpoint-activations]
                               [--save-interval SAVE_INTERVAL]
                               [--eval-interval EVAL_INTERVAL] [--save SAVE]
                               [--eval-iters EVAL_ITERS]
                               [--eval-batch-size EVAL_BATCH_SIZE]
                               [--split SPLIT]
                               [--deepspeed_config DEEPSPEED_CONFIG]
                               [--skip-init] [--seed SEED]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: argument --model-parallel-size: invalid int value: 'finetune'
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--local_rank LOCAL_RANK]
                               [--experiment-name finetune- EXPERIMENT_NAME FINETUNE_]
                               [--model-parallel-size MODEL_PARALLEL_SIZE]
                               [--train-iters TRAIN_ITERS]
                               [--resume-dataloader] [--train-data TRAIN_DATA]
                               [--valid-data VALID_DATA]
                               [--distributed-backend DISTRIBUTED_BACKEND]
                               [--lr-decay-style LR_DECAY_STYLE]
                               [--warmup WARMUP] [--checkpoint-activations]
                               [--save-interval SAVE_INTERVAL]
                               [--eval-interval EVAL_INTERVAL] [--save SAVE]
                               [--eval-iters EVAL_ITERS]
                               [--eval-batch-size EVAL_BATCH_SIZE]
                               [--split SPLIT]
                               [--deepspeed_config DEEPSPEED_CONFIG]
                               [--skip-init] [--seed SEED]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: argument --model-parallel-size: invalid int value: 'finetune'
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--local_rank LOCAL_RANK]
                               [--experiment-name finetune- EXPERIMENT_NAME FINETUNE_]
                               [--model-parallel-size MODEL_PARALLEL_SIZE]
                               [--train-iters TRAIN_ITERS]
                               [--resume-dataloader] [--train-data TRAIN_DATA]
                               [--valid-data VALID_DATA]
                               [--distributed-backend DISTRIBUTED_BACKEND]
                               [--lr-decay-style LR_DECAY_STYLE]
                               [--warmup WARMUP] [--checkpoint-activations]
                               [--save-interval SAVE_INTERVAL]
                               [--eval-interval EVAL_INTERVAL] [--save SAVE]
                               [--eval-iters EVAL_ITERS]
                               [--eval-batch-size EVAL_BATCH_SIZE]
                               [--split SPLIT]
                               [--deepspeed_config DEEPSPEED_CONFIG]
                               [--skip-init] [--seed SEED]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: argument --model-parallel-size: invalid int value: 'finetune'
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--local_rank LOCAL_RANK]
                               [--experiment-name finetune- EXPERIMENT_NAME FINETUNE_]
                               [--model-parallel-size MODEL_PARALLEL_SIZE]
                               [--train-iters TRAIN_ITERS]
                               [--resume-dataloader] [--train-data TRAIN_DATA]
                               [--valid-data VALID_DATA]
                               [--distributed-backend DISTRIBUTED_BACKEND]
                               [--lr-decay-style LR_DECAY_STYLE]
                               [--warmup WARMUP] [--checkpoint-activations]
                               [--save-interval SAVE_INTERVAL]
                               [--eval-interval EVAL_INTERVAL] [--save SAVE]
                               [--eval-iters EVAL_ITERS]
                               [--eval-batch-size EVAL_BATCH_SIZE]
                               [--split SPLIT]
                               [--deepspeed_config DEEPSPEED_CONFIG]
                               [--skip-init] [--seed SEED]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: argument --model-parallel-size: invalid int value: 'finetune'
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--local_rank LOCAL_RANK]
                               [--experiment-name finetune- EXPERIMENT_NAME FINETUNE_]
                               [--model-parallel-size MODEL_PARALLEL_SIZE]
                               [--train-iters TRAIN_ITERS]
                               [--resume-dataloader] [--train-data TRAIN_DATA]
                               [--valid-data VALID_DATA]
                               [--distributed-backend DISTRIBUTED_BACKEND]
                               [--lr-decay-style LR_DECAY_STYLE]
                               [--warmup WARMUP] [--checkpoint-activations]
                               [--save-interval SAVE_INTERVAL]
                               [--eval-interval EVAL_INTERVAL] [--save SAVE]
                               [--eval-iters EVAL_ITERS]
                               [--eval-batch-size EVAL_BATCH_SIZE]
                               [--split SPLIT]
                               [--deepspeed_config DEEPSPEED_CONFIG]
                               [--skip-init] [--seed SEED]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: argument --model-parallel-size: invalid int value: 'finetune'
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--local_rank LOCAL_RANK]
                               [--experiment-name finetune- EXPERIMENT_NAME FINETUNE_]
                               [--model-parallel-size MODEL_PARALLEL_SIZE]
                               [--train-iters TRAIN_ITERS]
                               [--resume-dataloader] [--train-data TRAIN_DATA]
                               [--valid-data VALID_DATA]
                               [--distributed-backend DISTRIBUTED_BACKEND]
                               [--lr-decay-style LR_DECAY_STYLE]
                               [--warmup WARMUP] [--checkpoint-activations]
                               [--save-interval SAVE_INTERVAL]
                               [--eval-interval EVAL_INTERVAL] [--save SAVE]
                               [--eval-iters EVAL_ITERS]
                               [--eval-batch-size EVAL_BATCH_SIZE]
                               [--split SPLIT]
                               [--deepspeed_config DEEPSPEED_CONFIG]
                               [--skip-init] [--seed SEED]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: argument --model-parallel-size: invalid int value: 'finetune'
usage: finetune_cogvlm_demo.py [--max_length MAX_LENGTH]
                               [--ignore_pad_token_for_loss]
                               [--version VERSION]
                               [--from_pretrained FROM_PRETRAINED]
                               [--local_tokenizer LOCAL_TOKENIZER]
                               [--vit_checkpoint_activations]
                               [--data_path DATA_PATH]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS]
                               [--local_rank LOCAL_RANK]
                               [--experiment-name finetune- EXPERIMENT_NAME FINETUNE_]
                               [--model-parallel-size MODEL_PARALLEL_SIZE]
                               [--train-iters TRAIN_ITERS]
                               [--resume-dataloader] [--train-data TRAIN_DATA]
                               [--valid-data VALID_DATA]
                               [--distributed-backend DISTRIBUTED_BACKEND]
                               [--lr-decay-style LR_DECAY_STYLE]
                               [--warmup WARMUP] [--checkpoint-activations]
                               [--save-interval SAVE_INTERVAL]
                               [--eval-interval EVAL_INTERVAL] [--save SAVE]
                               [--eval-iters EVAL_ITERS]
                               [--eval-batch-size EVAL_BATCH_SIZE]
                               [--split SPLIT]
                               [--deepspeed_config DEEPSPEED_CONFIG]
                               [--skip-init] [--seed SEED]
                               [--pre_seq_len PRE_SEQ_LEN]
                               [--lora_rank LORA_RANK] [--use_ptuning]
                               [--use_lora] [--use_qlora]
                               [--layer_range LAYER_RANGE [LAYER_RANGE ...]]
                               [--image_length IMAGE_LENGTH]
                               [--eva_args EVA_ARGS]
                               [--bos-token-id BOS_TOKEN_ID]
                               [--eos-token-id EOS_TOKEN_ID]
                               [--pad-token-id PAD_TOKEN_ID]
finetune_cogvlm_demo.py: error: argument --model-parallel-size: invalid int value: 'finetune'
[2024-02-14 17:34:59,345] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 13632
[2024-02-14 17:34:59,348] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 13633
[2024-02-14 17:34:59,349] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 13634
[2024-02-14 17:34:59,350] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 13635
[2024-02-14 17:34:59,350] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 13636
[2024-02-14 17:34:59,351] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 13637
[2024-02-14 17:34:59,352] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 13638
[2024-02-14 17:34:59,352] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 13639
[2024-02-14 17:34:59,353] [ERROR] [launch.py:322:sigkill_handler] ['/opt/conda/bin/python', '-u', '/CogVLM/finetune_demo/finetune_cogvlm_demo.py', '--local_rank=7', '--experiment-name', 'finetune-/workspace/cogvlm-chat-v1.1/1', '--model-parallel-size', '8', '--mode', 'finetune', '--train-iters', '2000', '--resume-dataloader', '--from_pretrained', '/workspace/cogvlm-chat-v1.1/1', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/workspace/models--lmsys--vicuna-7b-v1.5', '--version', 'chat_old', '--train-data', '/Dataset/train', '--valid-data', '/Dataset/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'test_config_bf16.json', '--skip-init', '--seed', '2023'] exits with return code = 2


**I have introduced these arguments in finetune_cogvlm_demo:**

if __name__ == '__main__':
    py_parser = argparse.ArgumentParser(add_help=False)
    py_parser.add_argument('--max_length', type=int)
    py_parser.add_argument('--ignore_pad_token_for_loss', action='store_false')
    py_parser.add_argument("--version", type=str, default="chat_old", help='version to interact with')
    py_parser.add_argument("--from_pretrained", type=str, default="/workspace/cogvlm-chat-v1.1/", help='pretrained ckpt')
    py_parser.add_argument("--local_tokenizer", type=str, default="/workspace/models--lmsys--vicuna-7b-v1.5", help='tokenizer path')
    py_parser.add_argument("--vit_checkpoint_activations", action='store_true')
    py_parser.add_argument('--data_path', type=str, help='Path to the dataset directory')
    py_parser.add_argument('--batch_size', type=int, default=4, help='Batch size for training')
    py_parser.add_argument('--num_workers', type=int, default=4, help='Number of workers for data loading')
    py_parser.add_argument('--local_rank', type=int, default=-1, help='local rank passed from distributed launcher')
    py_parser.add_argument('--experiment-name finetune-', type=str, default='Bebeto', help='Experiment name for saving models and logs')
    py_parser.add_argument('--model-parallel-size', type=int, default=8, help='Model parallel size')
    py_parser.add_argument('--train-iters', type=int, default=1000, help='Number of training iterations')
    py_parser.add_argument('--resume-dataloader', action='store_true', help='Resume data loader from checkpoint')
    py_parser.add_argument('--train-data', type=str, help='Path to training data')
    py_parser.add_argument('--valid-data', type=str, help='Path to validation data')
    py_parser.add_argument('--distributed-backend', type=str, default='nccl', help='Distributed backend type')
    py_parser.add_argument('--lr-decay-style', type=str, default='cosine', help='Learning rate decay style')
    py_parser.add_argument('--warmup', type=float, default=0.01, help='Warmup fraction of total iterations')
    py_parser.add_argument('--checkpoint-activations', action='store_true', help='Enable checkpoint activations')
    py_parser.add_argument('--save-interval', type=int, default=100, help='Model save interval')
    py_parser.add_argument('--eval-interval', type=int, default=100, help='Evaluation interval')
    py_parser.add_argument('--save', type=str, help='Save directory')
    py_parser.add_argument('--eval-iters', type=int, default=10, help='Number of iterations for evaluation')
    py_parser.add_argument('--eval-batch-size', type=int, default=1, help='Batch size for evaluation')
    py_parser.add_argument('--split', type=float, default=1.0, help='Split size for training/validation')
    py_parser.add_argument('--deepspeed_config', type=str, help='Path to DeepSpeed config file')
    py_parser.add_argument('--skip-init', action='store_true', help='Skip initialization, useful for super-resolution')
    py_parser.add_argument('--seed', type=int, default=42, help='Random seed for reproducibility')
    FineTuneTrainCogVLMModel.add_model_specific_args(py_parser)
    args = py_parser.parse_args()
    if args.use_qlora:
        args.device = 'cpu'

**Comment by Baggiorobertozoba** [comment]
Solved by adding the py parser add argument for mode.
